---
server:
    install: '1'
    packages: [vim, git]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant/www
    servername: cw.dev
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: admin
    password: '1234'
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-gd, php5-mysql]
    peclpackages: [PDO]
xdebug:
    install: '1'
composer:
    install: '1'

